service: clinic-server
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-jetpack
  - serverless-dotenv-plugin
  - serverless-layers
  - serverless-s3-deploy

custom:
  serverless-layers:  
    packageManager: yarn
    dependenciesPath: ./package.json
    layersDeploymentBucket: ${param:DeploymentArtifactBucket}
  s3Deploy:
    bucket: ${param:DeploymentArtifactBucket}
    path: pharm-server/${self:provider.stage}

provider:
 name: aws
 runtime: nodejs16.x
 stage: development
 region: eu-west-2
 deploymentMethod: direct
 environment:
  # - With the serverless-dotenv-plugin enabled, all variables in .env are automatically imported
 httpApi: 
   cors:
     allowedOrigins: ${param:AllowedOrigins}  
     allowedHeaders:
       - Content-Type
       - Authorization
     allowedMethods: "*"
     allowCredentials: true
     exposedResponseHeaders:
       - Special-Response-Header
       - Access-Control-Allow-Origin
     maxAge: 6000 # In seconds

params:
  production:
    Env: prod
    DomainNames: clinic.firdcare.click
    AllowedOrigins: https://clinic.firdcare.click
    DeploymentArtifactBucket: clinic-prod-deployment-artifacts
    CertificateArn: arn:aws:acm:us-east-1:665778208875:certificate/20426264-686e-464d-ae8b-d01d8a6d5069 # Certificate for firdcare.click
  development:
    Env: dev
    DomainNames: clinic-dev.firdcare.click
    AllowedOrigins: https://clinic-dev.firdcare.click
    DeploymentArtifactBucket: clinic-dev-deployment-artifacts
    CertificateArn: arn:aws:acm:us-east-1:665778208875:certificate/20426264-686e-464d-ae8b-d01d8a6d5069 # Certificate for firdcare.click

functions:
 api:
   handler: dist/lambda.handler
   timeout: 30
   events:
     - httpApi: "*"

resources: 
  - ${file(resources/app-resources.yml)}

package:
  exclude:
    - node_modules/**
    - migrations/**
    - seeders/**   
    - tmp/** 
    - src/**