version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LambAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19kkb6sag4e3k"
s3_prefix = "LambAPI"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
