AWSTemplateFormatVersion: '2010-09-09'

Parameters: 
  DbUsername: 
    Description: The database master username
    Type: String
    MinLength: 8
    ConstraintDescription: The username must be 8 charaters or more
    NoEcho: true
  DbPassword: 
    Description: The database master password
    Type: String
    MinLength: 8
    ConstraintDescription: The password must be 8 charaters or more
    NoEcho: true

Resources:
  SongsDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: songs-database
      PubliclyAccessible: true
      StorageType: gp2
      MasterUsername: !Ref DbUsername 
      MasterUserPassword: !Ref DbPassword 
      Engine: mysql
      EngineVersion: 8.0.28

Outputs: 
  DatabaseHost: 
    Description: The endpoint for the database
    Value: !GetAtt SongsDatabase.Endpoint.Address